# Docker ImageをビルドするためのCompose File
services:
  web:
    image: ${WEB_IMAGE}:${TAG:-latest}
    build:
      context: ../platform-web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

  api:
    image: ${API_IMAGE}:${TAG:-latest}
    build:
      context: ../platform-api
      dockerfile: Dockerfile
