'use client'

import type { ReactNode } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { CodeBlock } from '@/components/features/CodeBlock'
import { slugify } from '@/components/features/TableOfContents'

interface ContentRendererProps {
  markdown: string
}

/**
 * Fix markdown generated by older sync logic before recursive child-fetching
 * was in place:
 * 1. Strip HTML comment placeholders (e.g. <!-- table -->)
 * 2. Strip literal <br /> / <br> shown as text (react-markdown escapes
 *    HTML by default when rehype-raw is not used)
 * 3. Insert blank line between end of a list and the next paragraph so
 *    CommonMark parsers don't treat it as a lazy continuation of the last
 *    list item (which would make the paragraph invisible / swallowed).
 */
function preprocessMarkdown(md: string): string {
  let result = md
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^<br\s*\/?>\s*$/gm, '')

  const inputLines = result.split('\n')
  const out: string[] = []

  for (let i = 0; i < inputLines.length; i++) {
    const line = inputLines[i]
    out.push(line)

    const isListItem = /^[-*+] /.test(line) || /^\d+\. /.test(line)
    if (isListItem && i + 1 < inputLines.length) {
      const next = inputLines[i + 1]
      const nextIsListOrBlank =
        next === '' || /^[-*+] /.test(next) || /^\d+\. /.test(next)
      if (!nextIsListOrBlank) {
        out.push('')
      }
    }
  }

  return out.join('\n')
}

/**
 * Extract a file-path caption from the first line of a code block.
 * Matches: "// path foo.ts", "# path foo.py", "<!-- path foo.html -->", slash-star path foo.css star-slash
 */
function extractCaption(code: string): { caption: string | undefined; cleanCode: string } {
  const newlineIdx = code.indexOf('\n')
  const firstLine = newlineIdx === -1 ? code : code.slice(0, newlineIdx)
  const rest = newlineIdx === -1 ? '' : code.slice(newlineIdx + 1)
  const m = firstLine.match(/^\s*(?:\/\/|#|<!--|\/\*)\s+path\s+(.+?)\s*(?:-->|\*\/)?\s*$/)
  if (m) return { caption: m[1].trim(), cleanCode: rest }
  return { caption: undefined, cleanCode: code }
}

function nodeToText(node: ReactNode): string {
  if (typeof node === 'string' || typeof node === 'number') return String(node)
  if (Array.isArray(node)) return node.map(nodeToText).join('')
  if (node !== null && typeof node === 'object' && 'props' in node) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return nodeToText((node as any).props?.children)
  }
  return ''
}

export function ContentRenderer({ markdown }: ContentRendererProps) {
  const processed = preprocessMarkdown(markdown)
  return (
    <div>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ children }) => (
            <h1
              id={slugify(nodeToText(children))}
              className="mb-4 mt-8 text-2xl font-bold tracking-tight first:mt-0"
              style={{ color: '#e5eefc', letterSpacing: '-0.4px' }}
            >
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2
              id={slugify(nodeToText(children))}
              className="mb-3 mt-7 text-xl font-semibold tracking-tight first:mt-0"
              style={{ color: '#e5eefc' }}
            >
              {children}
            </h2>
          ),
          h3: ({ children }) => (
            <h3
              id={slugify(nodeToText(children))}
              className="mb-2 mt-6 text-lg font-semibold first:mt-0"
              style={{ color: '#dce8ff' }}
            >
              {children}
            </h3>
          ),
          p: ({ children }) => (
            <p className="mb-4 leading-relaxed" style={{ color: '#9fb0cc' }}>
              {children}
            </p>
          ),
          ul: ({ children }) => (
            <ul className="mb-4 list-disc space-y-1.5 pl-5" style={{ color: '#9fb0cc' }}>
              {children}
            </ul>
          ),
          ol: ({ children }) => (
            <ol className="mb-4 list-decimal space-y-1.5 pl-5" style={{ color: '#9fb0cc' }}>
              {children}
            </ol>
          ),
          li: ({ children }) => (
            <li className="leading-relaxed" style={{ color: '#9fb0cc' }}>
              {children}
            </li>
          ),
          blockquote: ({ children }) => (
            <blockquote
              className="mb-4 border-l-4 pl-4 italic"
              style={{ borderColor: 'rgba(124,58,237,.4)', color: '#9fb0cc' }}
            >
              {children}
            </blockquote>
          ),
          hr: () => (
            <hr className="my-6" style={{ borderColor: 'rgba(148,163,184,.18)' }} />
          ),
          img: ({ src, alt }) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={src}
              alt={alt ?? ''}
              className="my-4 max-w-full rounded-xl"
              style={{ border: '1px solid rgba(148,163,184,.18)' }}
            />
          ),
          a: ({ href, children }) => (
            <a
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              className="underline transition-colors hover:opacity-80"
              style={{ color: '#67e8f9' }}
            >
              {children}
            </a>
          ),
          table: ({ children }) => (
            <div
              className="mb-6 overflow-x-auto rounded-xl"
              style={{ border: '1px solid rgba(148,163,184,.14)' }}
            >
              <table className="w-full border-collapse text-sm" style={{ color: '#9fb0cc' }}>
                {children}
              </table>
            </div>
          ),
          thead: ({ children }) => (
            <thead style={{ background: 'rgba(148,163,184,.08)' }}>{children}</thead>
          ),
          tbody: ({ children }) => <tbody>{children}</tbody>,
          tr: ({ children }) => (
            <tr style={{ borderBottom: '1px solid rgba(148,163,184,.10)' }}>{children}</tr>
          ),
          th: ({ children }) => (
            <th
              className="px-4 py-2.5 text-left font-semibold"
              style={{ color: '#dce8ff', borderBottom: '1px solid rgba(148,163,184,.18)' }}
            >
              {children}
            </th>
          ),
          td: ({ children }) => (
            <td className="px-4 py-2.5" style={{ color: '#9fb0cc' }}>
              {children}
            </td>
          ),
          code: ({ className, children, ...props }) => {
            // Inline code (no language class)
            if (!className) {
              return (
                <code
                  className="rounded px-1.5 py-0.5 font-mono text-sm"
                  style={{
                    background: 'rgba(2,6,23,.60)',
                    color: '#7dd3fc',
                    border: '1px solid rgba(148,163,184,.12)',
                  }}
                  {...props}
                >
                  {children}
                </code>
              )
            }
            return <code className={className} {...props}>{children}</code>
          },
          pre: ({ children }) => {
            // Extract language and raw code string from the nested <code> element
            const codeEl =
              children !== null &&
              typeof children === 'object' &&
              'props' in children
                ? (children as { props: { className?: string; children?: unknown } }).props
                : null

            const rawCode = String(codeEl?.children ?? '').replace(/\n$/, '')
            const langMatch = /language-(\w+)/.exec(codeEl?.className ?? '')
            const language = langMatch?.[1]
            const { caption, cleanCode } = extractCaption(rawCode)

            return (
              <div className="mb-4">
                <CodeBlock code={cleanCode} language={language} caption={caption} />
              </div>
            )
          },
        }}
      >
        {processed}
      </ReactMarkdown>
    </div>
  )
}
